[project]
name = "image-stitching"
version = "0.1.0"
description = "Image stitching educational project"
authors = [
    {name = "Vladislav Tananaev", email = "idlogrus@gmail.com"}
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
